name: Nightly Google Finance Page Runs

on:
  schedule:
    - cron: '0 * * * *'  # Test run every hour

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Run tests
      env:
        DISPLAY: :99.0
      run: |
        xvfb-run -a --server-args="-screen 0 1920x1080x24" pytest -v -s
